export const ITEMS = [
  // FURNITURE (20 items)
  { id: 'sofa-lg',        name: 'Sofa / Couch (large)',          category: 'Furniture',      cy: 2.5,  surcharge: 0,   icon: '🛋️' },
  { id: 'sofa-sm',        name: 'Sofa / Couch (small)',          category: 'Furniture',      cy: 2.0,  surcharge: 0,   icon: '🛋️' },
  { id: 'loveseat',       name: 'Loveseat',                      category: 'Furniture',      cy: 1.5,  surcharge: 0,   icon: '🛋️' },
  { id: 'sectional',      name: 'Sectional (per section)',       category: 'Furniture',      cy: 2.0,  surcharge: 0,   icon: '🛋️' },
  { id: 'recliner',       name: 'Recliner / Armchair',           category: 'Furniture',      cy: 1.5,  surcharge: 0,   icon: '🪑' },
  { id: 'coffee-table',   name: 'Coffee Table',                  category: 'Furniture',      cy: 0.75, surcharge: 0,   icon: '🪵' },
  { id: 'dining-table',   name: 'Dining Table',                  category: 'Furniture',      cy: 2.0,  surcharge: 0,   icon: '🍽️' },
  { id: 'dining-chair',   name: 'Dining Chair (each)',           category: 'Furniture',      cy: 0.5,  surcharge: 0,   icon: '🪑' },
  { id: 'dresser-lg',     name: 'Dresser (large)',               category: 'Furniture',      cy: 2.0,  surcharge: 0,   icon: '🗄️' },
  { id: 'dresser-sm',     name: 'Dresser (small)',               category: 'Furniture',      cy: 1.25, surcharge: 0,   icon: '🗄️' },
  { id: 'bookshelf',      name: 'Bookshelf',                     category: 'Furniture',      cy: 1.0,  surcharge: 0,   icon: '📚' },
  { id: 'desk',           name: 'Desk',                          category: 'Furniture',      cy: 1.5,  surcharge: 0,   icon: '🖥️' },
  { id: 'bed-king',       name: 'Bed Frame (King)',              category: 'Furniture',      cy: 2.0,  surcharge: 0,   icon: '🛏️' },
  { id: 'bed-queen',      name: 'Bed Frame (Queen)',             category: 'Furniture',      cy: 1.5,  surcharge: 0,   icon: '🛏️' },
  { id: 'bed-twin',       name: 'Bed Frame (Twin/Full)',         category: 'Furniture',      cy: 1.0,  surcharge: 0,   icon: '🛏️' },
  { id: 'nightstand',     name: 'Nightstand',                    category: 'Furniture',      cy: 0.5,  surcharge: 0,   icon: '🪵' },
  { id: 'wardrobe',       name: 'Wardrobe / Armoire',            category: 'Furniture',      cy: 3.0,  surcharge: 0,   icon: '🗄️' },
  { id: 'filing-cabinet', name: 'Filing Cabinet',                category: 'Furniture',      cy: 1.0,  surcharge: 0,   icon: '🗃️' },
  { id: 'office-chair',   name: 'Office Chair',                  category: 'Furniture',      cy: 1.0,  surcharge: 0,   icon: '🪑' },
  { id: 'tv-stand',       name: 'TV Stand / Entertainment Center', category: 'Furniture',   cy: 1.5,  surcharge: 0,   icon: '📺' },
  // MATTRESSES (7 items)
  { id: 'mattress-king',  name: 'Mattress (King)',               category: 'Mattresses',     cy: 1.5,  surcharge: 45,  surchargeLabel: 'Mattress disposal fee',  icon: '🛏️' },
  { id: 'mattress-queen', name: 'Mattress (Queen)',              category: 'Mattresses',     cy: 1.25, surcharge: 45,  surchargeLabel: 'Mattress disposal fee',  icon: '🛏️' },
  { id: 'mattress-full',  name: 'Mattress (Full)',               category: 'Mattresses',     cy: 1.0,  surcharge: 40,  surchargeLabel: 'Mattress disposal fee',  icon: '🛏️' },
  { id: 'mattress-twin',  name: 'Mattress (Twin)',               category: 'Mattresses',     cy: 0.75, surcharge: 40,  surchargeLabel: 'Mattress disposal fee',  icon: '🛏️' },
  { id: 'boxspring-king', name: 'Box Spring (King)',             category: 'Mattresses',     cy: 1.0,  surcharge: 0,   icon: '🛏️' },
  { id: 'boxspring-queen',name: 'Box Spring (Queen)',            category: 'Mattresses',     cy: 0.75, surcharge: 0,   icon: '🛏️' },
  { id: 'boxspring-twin', name: 'Box Spring (Twin/Full)',        category: 'Mattresses',     cy: 0.5,  surcharge: 0,   icon: '🛏️' },
  // APPLIANCES (11 items)
  { id: 'fridge-lg',      name: 'Refrigerator (large)',          category: 'Appliances',     cy: 1.75, surcharge: 35,  surchargeLabel: 'Freon removal fee',      icon: '🧊' },
  { id: 'fridge-sm',      name: 'Refrigerator (mini/medium)',    category: 'Appliances',     cy: 1.0,  surcharge: 35,  surchargeLabel: 'Freon removal fee',      icon: '🧊' },
  { id: 'freezer',        name: 'Freezer (chest or upright)',    category: 'Appliances',     cy: 1.5,  surcharge: 35,  surchargeLabel: 'Freon removal fee',      icon: '🧊' },
  { id: 'washer',         name: 'Washing Machine',               category: 'Appliances',     cy: 1.25, surcharge: 0,   icon: '🫧' },
  { id: 'dryer',          name: 'Dryer',                         category: 'Appliances',     cy: 1.25, surcharge: 0,   icon: '🌀' },
  { id: 'stove',          name: 'Stove / Range',                 category: 'Appliances',     cy: 1.25, surcharge: 0,   icon: '🍳' },
  { id: 'dishwasher',     name: 'Dishwasher',                    category: 'Appliances',     cy: 0.75, surcharge: 0,   icon: '🍽️' },
  { id: 'microwave',      name: 'Microwave',                     category: 'Appliances',     cy: 0.3,  surcharge: 0,   icon: '📡' },
  { id: 'water-heater',   name: 'Water Heater',                  category: 'Appliances',     cy: 1.0,  surcharge: 0,   icon: '🔥' },
  { id: 'ac-window',      name: 'Window AC Unit',                category: 'Appliances',     cy: 0.5,  surcharge: 35,  surchargeLabel: 'Freon removal fee',      icon: '❄️' },
  { id: 'ac-portable',    name: 'Portable AC Unit',              category: 'Appliances',     cy: 0.75, surcharge: 35,  surchargeLabel: 'Freon removal fee',      icon: '❄️' },
  // ELECTRONICS (5 items)
  { id: 'tv-sm',          name: 'TV (27" and smaller)',          category: 'Electronics',    cy: 0.5,  surcharge: 25,  surchargeLabel: 'Electronics disposal fee', icon: '📺' },
  { id: 'tv-lg',          name: 'TV (28" and larger)',           category: 'Electronics',    cy: 0.75, surcharge: 35,  surchargeLabel: 'Electronics disposal fee', icon: '📺' },
  { id: 'monitor',        name: 'Computer Monitor',              category: 'Electronics',    cy: 0.25, surcharge: 15,  surchargeLabel: 'Electronics disposal fee', icon: '🖥️' },
  { id: 'computer',       name: 'Desktop Computer / Tower',      category: 'Electronics',    cy: 0.2,  surcharge: 0,   icon: '💻' },
  { id: 'printer',        name: 'Printer / Copier',              category: 'Electronics',    cy: 0.3,  surcharge: 0,   icon: '🖨️' },
  // OUTDOOR (12 items)
  { id: 'mower-push',     name: 'Push Lawnmower',                category: 'Outdoor',        cy: 0.75, surcharge: 0,   icon: '🌿' },
  { id: 'mower-riding',   name: 'Riding Lawnmower',              category: 'Outdoor',        cy: 4.0,  surcharge: 0,   icon: '🚜' },
  { id: 'bicycle',        name: 'Bicycle',                       category: 'Outdoor',        cy: 0.5,  surcharge: 0,   icon: '🚲' },
  { id: 'tire-no-rim',    name: 'Tire (no rim)',                 category: 'Outdoor',        cy: 0.5,  surcharge: 15,  surchargeLabel: 'Tire disposal fee',      icon: '🔄' },
  { id: 'tire-with-rim',  name: 'Tire (with rim)',               category: 'Outdoor',        cy: 0.75, surcharge: 20,  surchargeLabel: 'Tire/rim disposal fee',  icon: '🔄' },
  { id: 'grill',          name: 'BBQ Grill',                     category: 'Outdoor',        cy: 1.0,  surcharge: 0,   icon: '🔥' },
  { id: 'patio-chair',    name: 'Patio Chair (each)',            category: 'Outdoor',        cy: 0.5,  surcharge: 0,   icon: '🪑' },
  { id: 'patio-table',    name: 'Patio Table',                   category: 'Outdoor',        cy: 1.0,  surcharge: 0,   icon: '🪵' },
  { id: 'hot-tub',        name: 'Hot Tub',                       category: 'Outdoor',        cy: 8.0,  surcharge: 200, surchargeLabel: 'Hot tub demo & disposal', icon: '🛁' },
  { id: 'trampoline',     name: 'Trampoline',                    category: 'Outdoor',        cy: 3.0,  surcharge: 0,   icon: '⭕' },
  { id: 'swing-set',      name: 'Swing Set / Playset',           category: 'Outdoor',        cy: 4.0,  surcharge: 0,   icon: '🌳' },
  { id: 'shed-sm',        name: 'Small Shed (disassembled)',     category: 'Outdoor',        cy: 6.0,  surcharge: 0,   icon: '🏠' },
  // CONSTRUCTION (4 items)
  { id: 'drywall',        name: 'Drywall (per sheet)',           category: 'Construction',   cy: 0.1,  surcharge: 0,   icon: '🧱' },
  { id: 'lumber',         name: 'Lumber / Wood pile (per CY)',   category: 'Construction',   cy: 1.0,  surcharge: 0,   icon: '🪵' },
  { id: 'carpet-room',    name: 'Carpet (per room)',             category: 'Construction',   cy: 1.0,  surcharge: 0,   icon: '🏠' },
  { id: 'concrete',       name: 'Concrete / Heavy debris (CY)',  category: 'Construction',   cy: 1.0,  surcharge: 0,   icon: '⚓' },
  // MISCELLANEOUS (10 items)
  { id: 'piano-upright',  name: 'Piano (upright)',               category: 'Miscellaneous',  cy: 3.0,  surcharge: 125, surchargeLabel: 'Piano removal fee',      icon: '🎹' },
  { id: 'piano-grand',    name: 'Piano (grand)',                 category: 'Miscellaneous',  cy: 5.0,  surcharge: 200, surchargeLabel: 'Grand piano removal fee', icon: '🎹' },
  { id: 'safe',           name: 'Safe (small)',                  category: 'Miscellaneous',  cy: 0.75, surcharge: 0,   icon: '🔒' },
  { id: 'treadmill',      name: 'Treadmill / Elliptical',        category: 'Miscellaneous',  cy: 1.5,  surcharge: 0,   icon: '🏃' },
  { id: 'weight-bench',   name: 'Weight Bench / Gym Equipment',  category: 'Miscellaneous',  cy: 1.5,  surcharge: 0,   icon: '🏋️' },
  { id: 'boxes-sm',       name: 'Boxes / Bags (small, each)',    category: 'Miscellaneous',  cy: 0.15, surcharge: 0,   icon: '📦' },
  { id: 'boxes-lg',       name: 'Boxes / Bags (large, each)',    category: 'Miscellaneous',  cy: 0.3,  surcharge: 0,   icon: '📦' },
  { id: 'garbage-bags',   name: 'Garbage Bags (each)',           category: 'Miscellaneous',  cy: 0.1,  surcharge: 0,   icon: '🗑️' },
  { id: 'misc-sm',        name: 'Misc. Pile (small ~0.5 CY)',    category: 'Miscellaneous',  cy: 0.5,  surcharge: 0,   icon: '📦' },
  { id: 'misc-lg',        name: 'Misc. Pile (large ~1.5 CY)',    category: 'Miscellaneous',  cy: 1.5,  surcharge: 0,   icon: '📦' },
]

export const CATEGORIES = [
  'Furniture',
  'Mattresses',
  'Appliances',
  'Electronics',
  'Outdoor',
  'Construction',
  'Miscellaneous',
]

export const CATEGORY_ICONS = {
  Furniture: '🛋️',
  Mattresses: '🛏️',
  Appliances: '🧊',
  Electronics: '📺',
  Outdoor: '🌳',
  Construction: '🧱',
  Miscellaneous: '📦',
}
